import { Link, useNavigate } from "react-router-dom";
import { useEffect, useState } from "react";
import {
  registerUser,
  verifyOTP,
  resendOTP,
} from "../api/auth";

const Register = () => {
  const navigate = useNavigate();

  // ================= REGISTER STATES =================

  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");

  // ================= OTP STATES =================

  const [showOTP, setShowOTP] = useState(false);
  const [otp, setOtp] = useState("");
  const [otpLoading, setOtpLoading] = useState(false);
  const [resendLoading, setResendLoading] = useState(false);
  const [message, setMessage] = useState("");
  const [otpError, setOtpError] = useState("");

  // ================= RESEND TIMER =================

  const [resendTimer, setResendTimer] = useState(60);

  // ================= GENERAL STATES =================

  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  // ================= RESEND OTP TIMER =================

  useEffect(() => {
    if (!showOTP || resendTimer <= 0) {
      return;
    }

    const timer = setInterval(() => {
      setResendTimer((prev) => {
        if (prev <= 1) {
          clearInterval(timer);
          return 0;
        }

        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(timer);
  }, [showOTP]);

  // ================= REGISTER =================

  const handleSubmit = async (e) => {
    e.preventDefault();

    setError("");
    setMessage("");

    if (!name.trim()) {
      setError("Please enter your full name");
      return;
    }

    if (!email.trim()) {
      setError("Please enter your email address");
      return;
    }

    if (password !== confirmPassword) {
      setError("Passwords do not match");
      return;
    }

    if (password.length < 6) {
      setError("Password must contain at least 6 characters");
      return;
    }

    setLoading(true);

    try {
      const data = await registerUser({
        name,
        email,
        password,
      });

      // Registration successful
      // OTP has been generated by backend
      setShowOTP(true);

      // Start 60 second resend timer
      setResendTimer(60);

      setMessage(
        data.message ||
          "Registration successful. OTP sent to your email."
      );
    } catch (error) {
      setError(error.message);
    } finally {
      setLoading(false);
    }
  };

  // ================= VERIFY OTP =================

  const handleVerifyOTP = async (e) => {
    e.preventDefault();

    setOtpError("");
    setMessage("");

    if (!otp.trim()) {
      setOtpError("Please enter the OTP");
      return;
    }

    if (!/^\d{6}$/.test(otp)) {
      setOtpError("OTP must contain exactly 6 digits");
      return;
    }

    setOtpLoading(true);

    try {
      const data = await verifyOTP(email, otp);

      setMessage(
        data.message ||
          "Email verified successfully."
      );

      // Give user a moment to see success message
      setTimeout(() => {
        navigate("/login");
      }, 1200);

    } catch (error) {
      setOtpError(error.message);
    } finally {
      setOtpLoading(false);
    }
  };

  // ================= RESEND OTP =================

  const handleResendOTP = async () => {

    // Don't allow resend before timer finishes
    if (resendTimer > 0 || resendLoading) {
      return;
    }

    setOtpError("");
    setMessage("");
    setResendLoading(true);

    try {
      const data = await resendOTP(email);

      setMessage(
        data.message ||
          "A new OTP has been sent to your email."
      );

      setOtp("");

      // Restart timer after successful resend
      setResendTimer(60);

    } catch (error) {
      setOtpError(error.message);
    } finally {
      setResendLoading(false);
    }
  };

  // ================= OTP SCREEN =================

  if (showOTP) {
    return (
      <div className="min-h-screen bg-[#FFF8F1] flex items-center justify-center p-4">

        <div className="w-full max-w-md bg-white rounded-[28px] shadow-xl border border-orange-100 p-6 sm:p-10">

          {/* LOGO */}

          <div className="flex justify-center mb-8">
            <img
              src="/JanaMaan_logo.png"
              alt="JanaMaan - Powered by OZOCO"
              className="h-16 w-auto object-contain"
            />
          </div>

          {/* ICON */}

          <div className="flex justify-center mb-5">
            <div className="h-16 w-16 rounded-full bg-orange-50 border border-orange-100 flex items-center justify-center text-3xl">
              ✉️
            </div>
          </div>

          {/* HEADING */}

          <div className="text-center mb-7">

            <p className="text-sm font-semibold text-orange-600 mb-2">
              EMAIL VERIFICATION
            </p>

            <h2 className="text-3xl font-bold text-slate-900">
              Verify your email
            </h2>

            <p className="mt-3 text-sm text-slate-500 leading-relaxed">
              We've sent a 6-digit OTP to
            </p>

            <p className="mt-1 font-semibold text-slate-800 break-all">
              {email}
            </p>

          </div>

          {/* SUCCESS MESSAGE */}

          {message && (
            <div className="mb-4 rounded-xl border border-green-100 bg-green-50 px-4 py-3 text-sm text-green-700">
              {message}
            </div>
          )}

          {/* ERROR MESSAGE */}

          {otpError && (
            <div className="mb-4 rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-600">
              {otpError}
            </div>
          )}

          {/* OTP FORM */}

          <form
            onSubmit={handleVerifyOTP}
            className="space-y-5"
          >

            <div>

              <label
                htmlFor="otp"
                className="block text-sm font-medium text-slate-700 mb-2"
              >
                Enter OTP
              </label>

              <input
                id="otp"
                type="text"
                inputMode="numeric"
                autoComplete="one-time-code"
                maxLength={6}
                value={otp}
                onChange={(e) => {
                  const value = e.target.value
                    .replace(/\D/g, "")
                    .slice(0, 6);

                  setOtp(value);
                  setOtpError("");
                }}
                placeholder="Enter 6-digit OTP"
                className="w-full px-4 py-4 rounded-xl border border-slate-200 bg-slate-50 text-slate-900 text-center text-2xl font-semibold tracking-[0.5em] placeholder:text-slate-400 placeholder:text-sm placeholder:tracking-normal outline-none transition focus:bg-white focus:border-orange-500 focus:ring-4 focus:ring-orange-500/10"
              />

            </div>

            {/* VERIFY BUTTON */}

            <button
              type="submit"
              disabled={otpLoading}
              className="w-full py-3.5 rounded-xl bg-orange-600 text-white font-semibold shadow-lg shadow-orange-600/20 hover:bg-orange-700 hover:-translate-y-0.5 transition-all duration-200 disabled:opacity-60 disabled:cursor-not-allowed"
            >
              {otpLoading
                ? "Verifying..."
                : "Verify OTP →"}
            </button>

          </form>

          {/* RESEND */}

          <div className="mt-6 text-center">

            <p className="text-sm text-slate-500">
              Didn't receive the OTP?
            </p>

            {resendTimer > 0 ? (

              <p className="mt-2 text-sm text-slate-500">
                Resend OTP in{" "}
                <span className="font-semibold text-orange-600">
                  {resendTimer}s
                </span>
              </p>

            ) : (

              <button
                type="button"
                onClick={handleResendOTP}
                disabled={resendLoading}
                className="mt-2 font-semibold text-orange-600 hover:text-orange-700 transition disabled:opacity-50"
              >
                {resendLoading
                  ? "Sending..."
                  : "Resend OTP"}
              </button>

            )}

          </div>

          {/* BACK */}

          <div className="mt-6 text-center">

            <button
              type="button"
              onClick={() => {
                setShowOTP(false);
                setOtp("");
                setOtpError("");
                setMessage("");
                setResendTimer(60);
              }}
              className="text-sm text-slate-500 hover:text-orange-600 transition"
            >
              ← Back to registration
            </button>

          </div>

          {/* SECURITY */}

          <div className="mt-7 pt-5 border-t border-slate-100">

            <p className="text-xs text-center text-slate-400">
              🔒 Your email is verified securely with a one-time password.
            </p>

          </div>

        </div>

      </div>
    );
  }

  // ================= REGISTER SCREEN =================

  return (
    <div className="min-h-screen bg-[#FFF8F1] flex items-center justify-center p-4">

      <div className="w-full max-w-7xl min-h-[680px] bg-white rounded-[28px] shadow-xl overflow-hidden grid lg:grid-cols-2 border border-orange-100">

        {/* ================= LEFT SIDE ================= */}

        <div className="relative overflow-hidden px-8 py-10 sm:px-12 lg:px-14 flex flex-col justify-between">

          {/* Background Image */}

          <img
            src="/login-bg.jpg"
            alt="Citizen services"
            className="absolute inset-0 w-full h-full object-cover blur-[4px] scale-105"
          />

          {/* Dark Overlay */}

          <div className="absolute inset-0 bg-slate-950/60" />

          {/* Orange Gradient Overlay */}

          <div className="absolute inset-0 bg-gradient-to-br from-orange-950/40 via-transparent to-slate-950/50" />

          {/* LOGO */}

          <div className="relative z-10">

            <img
              src="/JanaMaan_logo.png"
              alt="JanaMaan - Powered by OZOCO"
              className="h-12 w-auto object-contain"
            />

            <p className="text-xs text-slate-300 mt-1 ml-1">
              AI Citizen Service Platform
            </p>

          </div>

          {/* MAIN CONTENT */}

          <div className="relative z-10 max-w-xl mt-12 lg:mt-0">

            <p className="text-sm font-semibold text-orange-300 uppercase tracking-wider mb-4">
              Join JanaMaan
            </p>

            <h2 className="text-4xl sm:text-5xl font-bold leading-[1.1] text-white">

              One platform.
              <br />

              <span className="text-orange-300">
                Every civic request.
              </span>

              <br />

              One simpler experience.

            </h2>

            <p className="mt-6 text-slate-200 text-base sm:text-lg leading-relaxed max-w-lg">
              Create your account to submit civic problems, receive
              service guidance, and track your requests from submission
              to resolution.
            </p>

            {/* FEATURES */}

            <div className="mt-8 space-y-4">

              {/* Feature 1 */}

              <div className="flex items-start gap-4">

                <div className="w-10 h-10 shrink-0 rounded-full bg-white/10 border border-white/20 backdrop-blur-sm flex items-center justify-center text-lg">
                  📝
                </div>

                <div>

                  <h3 className="font-semibold text-white">
                    Report Your Problem
                  </h3>

                  <p className="text-sm text-slate-300 mt-1">
                    Submit details, photos, or documents related to your issue.
                  </p>

                </div>

              </div>

              {/* Feature 2 */}

              <div className="flex items-start gap-4">

                <div className="w-10 h-10 shrink-0 rounded-full bg-white/10 border border-white/20 backdrop-blur-sm flex items-center justify-center text-lg">
                  ✨
                </div>

                <div>

                  <h3 className="font-semibold text-white">
                    Get the Right Service
                  </h3>

                  <p className="text-sm text-slate-300 mt-1">
                    AI helps understand your request and identify the appropriate service.
                  </p>

                </div>

              </div>

              {/* Feature 3 */}

              <div className="flex items-start gap-4">

                <div className="w-10 h-10 shrink-0 rounded-full bg-white/10 border border-white/20 backdrop-blur-sm flex items-center justify-center text-lg">
                  📍
                </div>

                <div>

                  <h3 className="font-semibold text-white">
                    Smart Department Routing
                  </h3>

                  <p className="text-sm text-slate-300 mt-1">
                    Your request can be routed to the appropriate department and jurisdiction.
                  </p>

                </div>

              </div>

              {/* Feature 4 */}

              <div className="flex items-start gap-4">

                <div className="w-10 h-10 shrink-0 rounded-full bg-white/10 border border-white/20 backdrop-blur-sm flex items-center justify-center text-lg">
                  🔎
                </div>

                <div>

                  <h3 className="font-semibold text-white">
                    Track Your Request
                  </h3>

                  <p className="text-sm text-slate-300 mt-1">
                    Stay informed about your request throughout the process.
                  </p>

                </div>

              </div>

            </div>

          </div>

          {/* FOOTER */}

          <div className="relative z-10 mt-10 flex items-center gap-6 text-xs text-slate-300">

            <span>Secure</span>

            <span className="w-1 h-1 rounded-full bg-orange-400" />

            <span>Transparent</span>

            <span className="w-1 h-1 rounded-full bg-orange-400" />

            <span>Citizen-focused</span>

          </div>

        </div>

        {/* ================= RIGHT SIDE ================= */}

        <div className="flex items-center justify-center px-6 py-10 sm:px-12 lg:px-16">

          <div className="w-full max-w-md">

            {/* MOBILE LOGO */}

            <div className="lg:hidden mb-8">

              <img
                src="/JanaMaan_logo.png"
                alt="JanaMaan - Powered by OZOCO"
                className="h-10 w-auto object-contain"
              />

            </div>

            {/* HEADING */}

            <div className="mb-7">

              <p className="text-sm font-semibold text-orange-600 mb-2">
                CREATE ACCOUNT
              </p>

              <h2 className="text-3xl sm:text-4xl font-bold text-slate-900">
                Get started with JanaMaan
              </h2>

              <p className="mt-3 text-slate-500">
                Create your account to access citizen services and manage your requests.
              </p>

            </div>

            {/* FORM */}

            <form
              onSubmit={handleSubmit}
              className="space-y-4"
            >

              {/* FULL NAME */}

              <div>

                <label
                  htmlFor="name"
                  className="block text-sm font-medium text-slate-700 mb-2"
                >
                  Full Name
                </label>

                <input
                  id="name"
                  type="text"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="Enter your full name"
                  required
                  className="w-full px-4 py-3.5 rounded-xl border border-slate-200 bg-slate-50 text-slate-900 placeholder:text-slate-400 outline-none transition focus:bg-white focus:border-orange-500 focus:ring-4 focus:ring-orange-500/10"
                />

              </div>

              {/* EMAIL */}

              <div>

                <label
                  htmlFor="email"
                  className="block text-sm font-medium text-slate-700 mb-2"
                >
                  Email Address
                </label>

                <input
                  id="email"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="Enter your email address"
                  required
                  className="w-full px-4 py-3.5 rounded-xl border border-slate-200 bg-slate-50 text-slate-900 placeholder:text-slate-400 outline-none transition focus:bg-white focus:border-orange-500 focus:ring-4 focus:ring-orange-500/10"
                />

              </div>

              {/* PASSWORD */}

              <div>

                <label
                  htmlFor="password"
                  className="block text-sm font-medium text-slate-700 mb-2"
                >
                  Password
                </label>

                <input
                  id="password"
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="Create a password"
                  required
                  className="w-full px-4 py-3.5 rounded-xl border border-slate-200 bg-slate-50 text-slate-900 placeholder:text-slate-400 outline-none transition focus:bg-white focus:border-orange-500 focus:ring-4 focus:ring-orange-500/10"
                />

              </div>

              {/* CONFIRM PASSWORD */}

              <div>

                <label
                  htmlFor="confirmPassword"
                  className="block text-sm font-medium text-slate-700 mb-2"
                >
                  Confirm Password
                </label>

                <input
                  id="confirmPassword"
                  type="password"
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  placeholder="Confirm your password"
                  required
                  className="w-full px-4 py-3.5 rounded-xl border border-slate-200 bg-slate-50 text-slate-900 placeholder:text-slate-400 outline-none transition focus:bg-white focus:border-orange-500 focus:ring-4 focus:ring-orange-500/10"
                />

              </div>

              {/* TERMS */}

              <div className="flex items-start gap-2 pt-1">

                <input
                  id="terms"
                  type="checkbox"
                  className="w-4 h-4 mt-0.5 accent-orange-600"
                />

                <label
                  htmlFor="terms"
                  className="text-sm text-slate-500 leading-relaxed"
                >
                  I agree to the{" "}

                  <span className="font-medium text-orange-600">
                    Terms of Service
                  </span>{" "}

                  and{" "}

                  <span className="font-medium text-orange-600">
                    Privacy Policy
                  </span>.
                </label>

              </div>

              {/* ERROR */}

              {error && (
                <p className="text-sm text-red-600 bg-red-50 border border-red-100 rounded-lg px-4 py-3">
                  {error}
                </p>
              )}

              {/* REGISTER BUTTON */}

              <button
                type="submit"
                disabled={loading}
                className="w-full py-3.5 rounded-xl bg-orange-600 text-white font-semibold shadow-lg shadow-orange-600/20 hover:bg-orange-700 hover:-translate-y-0.5 transition-all duration-200 disabled:opacity-60 disabled:cursor-not-allowed"
              >
                {loading
                  ? "Creating Account..."
                  : "Create Account →"}
              </button>

            </form>

            {/* LOGIN LINK */}

            <div className="mt-7 text-center">

              <p className="text-sm text-slate-500">

                Already have an account?{" "}

                <Link
                  to="/login"
                  className="font-semibold text-orange-600 hover:text-orange-700 transition"
                >
                  Sign in
                </Link>

              </p>

            </div>

            {/* SECURITY */}

            <div className="mt-7 pt-5 border-t border-slate-100">

              <p className="text-xs text-center text-slate-400">
                🔒 Your account information is protected with secure authentication.
              </p>

            </div>

          </div>

        </div>

      </div>

    </div>
  );
};

export default Register;